// swift-tools-version:5.9
import PackageDescription

// The prebuilt Rust core. The release workflow rewrites this block on tagged
// releases to point at GitHub release assets (url: + checksum:).
// RELEASE-BINARY-TARGET-BEGIN
#if os(Linux)
let cedarFFIBinaryTarget: Target = .binaryTarget(
    name: "CedarFFIBinary",
    path: "artifacts/CedarFFI.artifactbundle"
)
#else
let cedarFFIBinaryTarget: Target = .binaryTarget(
    name: "CedarFFIBinary",
    path: "artifacts/CedarFFI.xcframework"
)
#endif
// RELEASE-BINARY-TARGET-END

let package = Package(
    name: "swift-cedar",
    platforms: [
        .macOS(.v13),
        .iOS(.v16),
        .tvOS(.v16),
        .watchOS(.v9),
        .visionOS(.v1),
    ],
    products: [
        .library(name: "CedarPolicy", targets: ["CedarPolicy"])
    ],
    targets: [
        // Rust core (cedar-policy engine). Build locally with
        // scripts/build-xcframework.sh (Apple) or scripts/build-linux.sh (Linux,
        // Swift 6.3+). Release tags replace these with url:/checksum: pairs so
        // consumers don't need a Rust toolchain.
        cedarFFIBinaryTarget,
        // UniFFI-generated bindings (do not edit; regenerated by the build script)
        .target(
            name: "CedarFFI",
            dependencies: ["CedarFFIBinary"]
        ),
        .target(
            name: "CedarPolicy",
            dependencies: ["CedarFFI"]
        ),
        .testTarget(
            name: "CedarPolicyTests",
            dependencies: ["CedarPolicy"]
        ),
    ]
)
