// swift-tools-version:5.9
import PackageDescription

let package = Package(
    name: "swift-cedar",
    platforms: [
        .macOS(.v13),
        .iOS(.v16),
        .tvOS(.v16),
        .watchOS(.v9),
        .visionOS(.v1),
    ],
    products: [
        .library(name: "CedarPolicy", targets: ["CedarPolicy"])
    ],
    targets: [
        // Rust core (cedar-policy engine) — build with scripts/build-xcframework.sh
        .binaryTarget(
            name: "CedarFFIBinary",
            path: "artifacts/CedarFFI.xcframework"
        ),
        // UniFFI-generated bindings (do not edit; regenerated by the build script)
        .target(
            name: "CedarFFI",
            dependencies: ["CedarFFIBinary"]
        ),
        .target(
            name: "CedarPolicy",
            dependencies: ["CedarFFI"]
        ),
        .testTarget(
            name: "CedarPolicyTests",
            dependencies: ["CedarPolicy"]
        ),
    ]
)
