// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(CedarFFIFFI)
import CedarFFIFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_cedar_ffi_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_cedar_ffi_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }

    init(rawBufferPointer: UnsafeRawBufferPointer) {
        self.init(
            len: Int32(rawBufferPointer.count),
            data: rawBufferPointer.baseAddress?.assumingMemoryBound(to: UInt8.self)
        )
    }
}

// Converter for `&[u8]` / `[ByRef] bytes` arguments.
//
// Conforms to `FfiConverter` so the compiler enforces the full converter
// method set. Only the scope-bound `lower(_:_body:)` overload is sound —
// zero-copy byte buffers only flow foreign -> Rust, and only in argument
// position. The four protocol-witness methods (`lift`, `lower`, `read`,
// `write`) `fatalError` at runtime if anyone reaches them.
//
// The scope-bound `lower` takes a closure because the `ForeignBytes`
// pointer is only guaranteed valid for the duration of
// `Data.withUnsafeBytes`. Callers must run the full FFI call inside
// the closure body.
fileprivate enum FfiConverterByRefBytes: FfiConverter {
    typealias SwiftType = Data
    typealias FfiType = ForeignBytes

    static func lower<R>(_ value: Data, _ body: (ForeignBytes) throws -> R) rethrows -> R {
        return try value.withUnsafeBytes { rawBuf in
            try body(ForeignBytes(rawBufferPointer: rawBuf))
        }
    }

    static func lower(_ value: Data) -> ForeignBytes {
        fatalError("ByRef bytes cannot use the plain lower: returning ForeignBytes escapes the Data.withUnsafeBytes scope. Use the scope-bound lower(_:_body:) overload instead.")
    }

    static func lift(_ value: ForeignBytes) throws -> Data {
        fatalError("ByRef bytes cannot be lifted: zero-copy &[u8] only flows foreign->Rust")
    }

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Data {
        fatalError("ByRef bytes cannot be read from a buffer: zero-copy &[u8] is only supported in argument position, not nested in records/options/etc.")
    }

    static func write(_ value: Data, into buf: inout [UInt8]) {
        fatalError("ByRef bytes cannot be written to a buffer: zero-copy &[u8] is only supported in argument position, not nested in records/options/etc.")
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureCedarFfiInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
// Initial value and increment amount for handles. 
// These ensure that SWIFT handles always have the lowest bit set
fileprivate let UNIFFI_HANDLEMAP_INITIAL: UInt64 = 1
fileprivate let UNIFFI_HANDLEMAP_DELTA: UInt64 = 2

fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = UNIFFI_HANDLEMAP_INITIAL

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            return doInsert(obj)
        }
    }

    // Low-level insert function, this assumes `lock` is held.
    private func doInsert(_ obj: T) -> UInt64 {
        let handle = currentHandle
        currentHandle += UNIFFI_HANDLEMAP_DELTA
        map[handle] = obj
        return handle
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

     func clone(handle: UInt64) throws -> UInt64 {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return doInsert(obj)
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        // Use Swift's native UTF-8 decoder; `String(bytes:encoding:.utf8)` goes
        // through Foundation's NSString and silently strips a leading U+FEFF BOM.
        // Invalid UTF-8 substitutes U+FFFD instead of trapping (unreachable
        // given Rust's `String` invariant).
        return String(decoding: bytes, as: UTF8.self)
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        // See `lift` above for why we avoid Foundation's NSString-backed decoder here.
        return String(decoding: try readBytes(&buf, count: Int(len)), as: UTF8.self)
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}




/**
 * The Cedar authorization engine.
 */
public protocol FfiAuthorizerProtocol: AnyObject, Sendable {
    
    /**
     * Evaluate an authorization request against a policy set and entities.
     *
     * `context_json` is a JSON object (Cedar context JSON format) or None
     * for an empty context. If a schema is provided, the request is
     * validated against it.
     */
    func isAuthorized(principal: FfiEntityUid, action: FfiEntityUid, resource: FfiEntityUid, contextJson: String?, policies: FfiPolicySet, entities: FfiEntities, schema: FfiSchema?) throws  -> FfiResponse
    
}
/**
 * The Cedar authorization engine.
 */
open class FfiAuthorizer: FfiAuthorizerProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_cedar_ffi_fn_clone_ffiauthorizer(self.handle, $0) }
    }
public convenience init() {
    let handle =
        try! rustCall() {
        uniffiCallStatus in
    uniffi_cedar_ffi_fn_constructor_ffiauthorizer_new(uniffiCallStatus
    )
}
    self.init(unsafeFromHandle: handle)
}

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_cedar_ffi_fn_free_ffiauthorizer(handle, $0) }
    }

    

    
    /**
     * Evaluate an authorization request against a policy set and entities.
     *
     * `context_json` is a JSON object (Cedar context JSON format) or None
     * for an empty context. If a schema is provided, the request is
     * validated against it.
     */
open func isAuthorized(principal: FfiEntityUid, action: FfiEntityUid, resource: FfiEntityUid, contextJson: String?, policies: FfiPolicySet, entities: FfiEntities, schema: FfiSchema?)throws  -> FfiResponse  {
    return try  FfiConverterTypeFfiResponse_lift(try rustCallWithError(FfiConverterTypeCedarError_lift) {
        uniffiCallStatus in
    uniffi_cedar_ffi_fn_method_ffiauthorizer_is_authorized(
            self.uniffiCloneHandle(),
        FfiConverterTypeFfiEntityUid_lower(principal),
        FfiConverterTypeFfiEntityUid_lower(action),
        FfiConverterTypeFfiEntityUid_lower(resource),
        FfiConverterOptionString.lower(contextJson),
        FfiConverterTypeFfiPolicySet_lower(policies),
        FfiConverterTypeFfiEntities_lower(entities),
        FfiConverterOptionTypeFfiSchema.lower(schema),uniffiCallStatus
    )
})
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiAuthorizer: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = FfiAuthorizer

    public static func lift(_ handle: UInt64) throws -> FfiAuthorizer {
        return FfiAuthorizer(unsafeFromHandle: handle)
    }

    public static func lower(_ value: FfiAuthorizer) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiAuthorizer {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: FfiAuthorizer, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiAuthorizer_lift(_ handle: UInt64) throws -> FfiAuthorizer {
    return try FfiConverterTypeFfiAuthorizer.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiAuthorizer_lower(_ value: FfiAuthorizer) -> UInt64 {
    return FfiConverterTypeFfiAuthorizer.lower(value)
}






/**
 * The set of entities (principals, resources, parents, attributes) used
 * when evaluating an authorization request.
 */
public protocol FfiEntitiesProtocol: AnyObject, Sendable {
    
    func toJson() throws  -> String
    
}
/**
 * The set of entities (principals, resources, parents, attributes) used
 * when evaluating an authorization request.
 */
open class FfiEntities: FfiEntitiesProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_cedar_ffi_fn_clone_ffientities(self.handle, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_cedar_ffi_fn_free_ffientities(handle, $0) }
    }

    
public static func empty() -> FfiEntities  {
    return try!  FfiConverterTypeFfiEntities_lift(try! rustCall() {
        uniffiCallStatus in
    uniffi_cedar_ffi_fn_constructor_ffientities_empty(uniffiCallStatus
    )
})
}
    
    /**
     * Parse entities from the Cedar entities JSON format. If a schema is
     * provided, entities are validated against it.
     */
public static func fromJson(json: String, schema: FfiSchema?)throws  -> FfiEntities  {
    return try  FfiConverterTypeFfiEntities_lift(try rustCallWithError(FfiConverterTypeCedarError_lift) {
        uniffiCallStatus in
    uniffi_cedar_ffi_fn_constructor_ffientities_from_json(
        FfiConverterString.lower(json),
        FfiConverterOptionTypeFfiSchema.lower(schema),uniffiCallStatus
    )
})
}
    

    
open func toJson()throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeCedarError_lift) {
        uniffiCallStatus in
    uniffi_cedar_ffi_fn_method_ffientities_to_json(
            self.uniffiCloneHandle(),uniffiCallStatus
    )
})
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiEntities: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = FfiEntities

    public static func lift(_ handle: UInt64) throws -> FfiEntities {
        return FfiEntities(unsafeFromHandle: handle)
    }

    public static func lower(_ value: FfiEntities) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiEntities {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: FfiEntities, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiEntities_lift(_ handle: UInt64) throws -> FfiEntities {
    return try FfiConverterTypeFfiEntities.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiEntities_lower(_ value: FfiEntities) -> UInt64 {
    return FfiConverterTypeFfiEntities.lower(value)
}






/**
 * A single parsed Cedar policy.
 */
public protocol FfiPolicyProtocol: AnyObject, Sendable {
    
    /**
     * The value of an annotation on this policy, if present.
     */
    func annotation(key: String)  -> String?
    
    func id()  -> String
    
    func toCedar()  -> String
    
    /**
     * The policy rendered in the Cedar JSON policy format.
     */
    func toJson() throws  -> String
    
}
/**
 * A single parsed Cedar policy.
 */
open class FfiPolicy: FfiPolicyProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_cedar_ffi_fn_clone_ffipolicy(self.handle, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_cedar_ffi_fn_free_ffipolicy(handle, $0) }
    }

    
    /**
     * Build a policy from the Cedar JSON policy format.
     */
public static func fromJson(json: String, id: String?)throws  -> FfiPolicy  {
    return try  FfiConverterTypeFfiPolicy_lift(try rustCallWithError(FfiConverterTypeCedarError_lift) {
        uniffiCallStatus in
    uniffi_cedar_ffi_fn_constructor_ffipolicy_from_json(
        FfiConverterString.lower(json),
        FfiConverterOptionString.lower(id),uniffiCallStatus
    )
})
}
    
    /**
     * Parse a single policy (static or template) from Cedar source text.
     */
public static func parse(text: String, id: String?)throws  -> FfiPolicy  {
    return try  FfiConverterTypeFfiPolicy_lift(try rustCallWithError(FfiConverterTypeCedarError_lift) {
        uniffiCallStatus in
    uniffi_cedar_ffi_fn_constructor_ffipolicy_parse(
        FfiConverterString.lower(text),
        FfiConverterOptionString.lower(id),uniffiCallStatus
    )
})
}
    

    
    /**
     * The value of an annotation on this policy, if present.
     */
open func annotation(key: String) -> String?  {
    return try!  FfiConverterOptionString.lift(try! rustCall() {
        uniffiCallStatus in
    uniffi_cedar_ffi_fn_method_ffipolicy_annotation(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(key),uniffiCallStatus
    )
})
}
    
open func id() -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
        uniffiCallStatus in
    uniffi_cedar_ffi_fn_method_ffipolicy_id(
            self.uniffiCloneHandle(),uniffiCallStatus
    )
})
}
    
open func toCedar() -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
        uniffiCallStatus in
    uniffi_cedar_ffi_fn_method_ffipolicy_to_cedar(
            self.uniffiCloneHandle(),uniffiCallStatus
    )
})
}
    
    /**
     * The policy rendered in the Cedar JSON policy format.
     */
open func toJson()throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeCedarError_lift) {
        uniffiCallStatus in
    uniffi_cedar_ffi_fn_method_ffipolicy_to_json(
            self.uniffiCloneHandle(),uniffiCallStatus
    )
})
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiPolicy: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = FfiPolicy

    public static func lift(_ handle: UInt64) throws -> FfiPolicy {
        return FfiPolicy(unsafeFromHandle: handle)
    }

    public static func lower(_ value: FfiPolicy) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiPolicy {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: FfiPolicy, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiPolicy_lift(_ handle: UInt64) throws -> FfiPolicy {
    return try FfiConverterTypeFfiPolicy.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiPolicy_lower(_ value: FfiPolicy) -> UInt64 {
    return FfiConverterTypeFfiPolicy.lower(value)
}






/**
 * A set of Cedar policies (and templates).
 */
public protocol FfiPolicySetProtocol: AnyObject, Sendable {
    
    func isEmpty()  -> Bool
    
    func policyIds()  -> [String]
    
    func toCedar()  -> String
    
}
/**
 * A set of Cedar policies (and templates).
 */
open class FfiPolicySet: FfiPolicySetProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_cedar_ffi_fn_clone_ffipolicyset(self.handle, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_cedar_ffi_fn_free_ffipolicyset(handle, $0) }
    }

    
public static func empty() -> FfiPolicySet  {
    return try!  FfiConverterTypeFfiPolicySet_lift(try! rustCall() {
        uniffiCallStatus in
    uniffi_cedar_ffi_fn_constructor_ffipolicyset_empty(uniffiCallStatus
    )
})
}
    
    /**
     * Build a policy set from individually parsed policies.
     */
public static func fromPolicies(policies: [FfiPolicy])throws  -> FfiPolicySet  {
    return try  FfiConverterTypeFfiPolicySet_lift(try rustCallWithError(FfiConverterTypeCedarError_lift) {
        uniffiCallStatus in
    uniffi_cedar_ffi_fn_constructor_ffipolicyset_from_policies(
        FfiConverterSequenceTypeFfiPolicy.lower(policies),uniffiCallStatus
    )
})
}
    
    /**
     * Parse a policy set from Cedar source text (may contain many policies).
     */
public static func parse(text: String)throws  -> FfiPolicySet  {
    return try  FfiConverterTypeFfiPolicySet_lift(try rustCallWithError(FfiConverterTypeCedarError_lift) {
        uniffiCallStatus in
    uniffi_cedar_ffi_fn_constructor_ffipolicyset_parse(
        FfiConverterString.lower(text),uniffiCallStatus
    )
})
}
    

    
open func isEmpty() -> Bool  {
    return try!  FfiConverterBool.lift(try! rustCall() {
        uniffiCallStatus in
    uniffi_cedar_ffi_fn_method_ffipolicyset_is_empty(
            self.uniffiCloneHandle(),uniffiCallStatus
    )
})
}
    
open func policyIds() -> [String]  {
    return try!  FfiConverterSequenceString.lift(try! rustCall() {
        uniffiCallStatus in
    uniffi_cedar_ffi_fn_method_ffipolicyset_policy_ids(
            self.uniffiCloneHandle(),uniffiCallStatus
    )
})
}
    
open func toCedar() -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
        uniffiCallStatus in
    uniffi_cedar_ffi_fn_method_ffipolicyset_to_cedar(
            self.uniffiCloneHandle(),uniffiCallStatus
    )
})
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiPolicySet: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = FfiPolicySet

    public static func lift(_ handle: UInt64) throws -> FfiPolicySet {
        return FfiPolicySet(unsafeFromHandle: handle)
    }

    public static func lower(_ value: FfiPolicySet) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiPolicySet {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: FfiPolicySet, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiPolicySet_lift(_ handle: UInt64) throws -> FfiPolicySet {
    return try FfiConverterTypeFfiPolicySet.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiPolicySet_lower(_ value: FfiPolicySet) -> UInt64 {
    return FfiConverterTypeFfiPolicySet.lower(value)
}






/**
 * A Cedar schema, used for request/entity validation and policy validation.
 */
public protocol FfiSchemaProtocol: AnyObject, Sendable {
    
}
/**
 * A Cedar schema, used for request/entity validation and policy validation.
 */
open class FfiSchema: FfiSchemaProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_cedar_ffi_fn_clone_ffischema(self.handle, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_cedar_ffi_fn_free_ffischema(handle, $0) }
    }

    
    /**
     * Parse a schema from the Cedar JSON schema format.
     */
public static func fromJson(json: String)throws  -> FfiSchema  {
    return try  FfiConverterTypeFfiSchema_lift(try rustCallWithError(FfiConverterTypeCedarError_lift) {
        uniffiCallStatus in
    uniffi_cedar_ffi_fn_constructor_ffischema_from_json(
        FfiConverterString.lower(json),uniffiCallStatus
    )
})
}
    
    /**
     * Parse a schema from the human-readable Cedar schema format.
     */
public static func parse(text: String)throws  -> FfiSchema  {
    return try  FfiConverterTypeFfiSchema_lift(try rustCallWithError(FfiConverterTypeCedarError_lift) {
        uniffiCallStatus in
    uniffi_cedar_ffi_fn_constructor_ffischema_parse(
        FfiConverterString.lower(text),uniffiCallStatus
    )
})
}
    

    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiSchema: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = FfiSchema

    public static func lift(_ handle: UInt64) throws -> FfiSchema {
        return FfiSchema(unsafeFromHandle: handle)
    }

    public static func lower(_ value: FfiSchema) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiSchema {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: FfiSchema, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiSchema_lift(_ handle: UInt64) throws -> FfiSchema {
    return try FfiConverterTypeFfiSchema.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiSchema_lower(_ value: FfiSchema) -> UInt64 {
    return FfiConverterTypeFfiSchema.lower(value)
}






/**
 * A symbolic compiler over a local cvc5 process.
 *
 * Stateless by construction: each query spawns its own solver, because a
 * long-lived SMT process is stateful, poisonable by one bad query, and would
 * have to be serialized behind a lock anyway. Spawning is negligible next to
 * solving, and these analyses run on policy writes, not on the request path.
 */
public protocol FfiSymbolicCompilerProtocol: AnyObject, Sendable {
    
    /**
     * Returns whether no request in `env` is allowed by both policy sets.
     *
     * `holds == false` means the sets overlap, and the counterexample is a
     * request both would allow.
     */
    func checkDisjoint(schema: FfiSchema, policiesA: FfiPolicySet, policiesB: FfiPolicySet, env: FfiRequestEnv, counterexample: Bool) async throws  -> FfiAnalysisResult
    
    /**
     * Returns whether every request in `env` allowed by `policies_a` is also
     * allowed by `policies_b` — subsumption.
     *
     * `holds == false` means the first set reaches something the second does
     * not, and the counterexample is such a request.
     */
    func checkImplies(schema: FfiSchema, policiesA: FfiPolicySet, policiesB: FfiPolicySet, env: FfiRequestEnv, counterexample: Bool) async throws  -> FfiAnalysisResult
    
}
/**
 * A symbolic compiler over a local cvc5 process.
 *
 * Stateless by construction: each query spawns its own solver, because a
 * long-lived SMT process is stateful, poisonable by one bad query, and would
 * have to be serialized behind a lock anyway. Spawning is negligible next to
 * solving, and these analyses run on policy writes, not on the request path.
 */
open class FfiSymbolicCompiler: FfiSymbolicCompilerProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_cedar_ffi_fn_clone_ffisymboliccompiler(self.handle, $0) }
    }
    /**
     * Build a compiler driving the cvc5 executable at `solver_path`.
     *
     * The path is explicit rather than read from the ambient `CVC5`
     * environment variable the way `LocalSolver::cvc5()` does: a server
     * deciding whether to fail closed needs to know *which* binary it is
     * about to trust, and inheriting it from the environment makes that
     * unanswerable.
     */
public convenience init(solverPath: String, timeoutMs: UInt32) {
    let handle =
        try! rustCall() {
        uniffiCallStatus in
    uniffi_cedar_ffi_fn_constructor_ffisymboliccompiler_new(
        FfiConverterString.lower(solverPath),
        FfiConverterUInt32.lower(timeoutMs),uniffiCallStatus
    )
}
    self.init(unsafeFromHandle: handle)
}

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_cedar_ffi_fn_free_ffisymboliccompiler(handle, $0) }
    }

    

    
    /**
     * Returns whether no request in `env` is allowed by both policy sets.
     *
     * `holds == false` means the sets overlap, and the counterexample is a
     * request both would allow.
     */
open func checkDisjoint(schema: FfiSchema, policiesA: FfiPolicySet, policiesB: FfiPolicySet, env: FfiRequestEnv, counterexample: Bool)async throws  -> FfiAnalysisResult  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_cedar_ffi_fn_method_ffisymboliccompiler_check_disjoint(
                        self.uniffiCloneHandle(),FfiConverterTypeFfiSchema_lower(schema),FfiConverterTypeFfiPolicySet_lower(policiesA),FfiConverterTypeFfiPolicySet_lower(policiesB),FfiConverterTypeFfiRequestEnv_lower(env),FfiConverterBool.lower(counterexample)
                )
            },
            pollFunc: ffi_cedar_ffi_rust_future_poll_rust_buffer,
            completeFunc: ffi_cedar_ffi_rust_future_complete_rust_buffer,
            freeFunc: ffi_cedar_ffi_rust_future_free_rust_buffer,
            liftFunc: FfiConverterTypeFfiAnalysisResult_lift,
            errorHandler: FfiConverterTypeCedarError_lift
        )
}
    
    /**
     * Returns whether every request in `env` allowed by `policies_a` is also
     * allowed by `policies_b` — subsumption.
     *
     * `holds == false` means the first set reaches something the second does
     * not, and the counterexample is such a request.
     */
open func checkImplies(schema: FfiSchema, policiesA: FfiPolicySet, policiesB: FfiPolicySet, env: FfiRequestEnv, counterexample: Bool)async throws  -> FfiAnalysisResult  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_cedar_ffi_fn_method_ffisymboliccompiler_check_implies(
                        self.uniffiCloneHandle(),FfiConverterTypeFfiSchema_lower(schema),FfiConverterTypeFfiPolicySet_lower(policiesA),FfiConverterTypeFfiPolicySet_lower(policiesB),FfiConverterTypeFfiRequestEnv_lower(env),FfiConverterBool.lower(counterexample)
                )
            },
            pollFunc: ffi_cedar_ffi_rust_future_poll_rust_buffer,
            completeFunc: ffi_cedar_ffi_rust_future_complete_rust_buffer,
            freeFunc: ffi_cedar_ffi_rust_future_free_rust_buffer,
            liftFunc: FfiConverterTypeFfiAnalysisResult_lift,
            errorHandler: FfiConverterTypeCedarError_lift
        )
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiSymbolicCompiler: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = FfiSymbolicCompiler

    public static func lift(_ handle: UInt64) throws -> FfiSymbolicCompiler {
        return FfiSymbolicCompiler(unsafeFromHandle: handle)
    }

    public static func lower(_ value: FfiSymbolicCompiler) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiSymbolicCompiler {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: FfiSymbolicCompiler, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiSymbolicCompiler_lift(_ handle: UInt64) throws -> FfiSymbolicCompiler {
    return try FfiConverterTypeFfiSymbolicCompiler.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiSymbolicCompiler_lower(_ value: FfiSymbolicCompiler) -> UInt64 {
    return FfiConverterTypeFfiSymbolicCompiler.lower(value)
}




/**
 * The answer to one analysis query.
 */
public struct FfiAnalysisResult: Equatable, Hashable {
    /**
     * Whether the property asked about holds.
     */
    public var holds: Bool
    /**
     * A concrete request violating the property, rendered for humans, when
     * the caller asked for one and the property does not hold.
     */
    public var counterexample: String?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * Whether the property asked about holds.
         */holds: Bool, 
        /**
         * A concrete request violating the property, rendered for humans, when
         * the caller asked for one and the property does not hold.
         */counterexample: String?) {
        self.holds = holds
        self.counterexample = counterexample
    }

    

    
}

#if compiler(>=6)
extension FfiAnalysisResult: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiAnalysisResult: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiAnalysisResult {
        return
            try FfiAnalysisResult(
                holds: FfiConverterBool.read(from: &buf), 
                counterexample: FfiConverterOptionString.read(from: &buf)
        )
    }

    public static func write(_ value: FfiAnalysisResult, into buf: inout [UInt8]) {
        FfiConverterBool.write(value.holds, into: &buf)
        FfiConverterOptionString.write(value.counterexample, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiAnalysisResult_lift(_ buf: RustBuffer) throws -> FfiAnalysisResult {
    return try FfiConverterTypeFfiAnalysisResult.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiAnalysisResult_lower(_ value: FfiAnalysisResult) -> RustBuffer {
    return FfiConverterTypeFfiAnalysisResult.lower(value)
}


/**
 * A Cedar entity reference, e.g. `User::"alice"`.
 */
public struct FfiEntityUid: Equatable, Hashable {
    /**
     * Fully-qualified entity type, e.g. `PhotoApp::User`.
     */
    public var typeName: String
    /**
     * The entity id (unescaped), e.g. `alice`.
     */
    public var id: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * Fully-qualified entity type, e.g. `PhotoApp::User`.
         */typeName: String, 
        /**
         * The entity id (unescaped), e.g. `alice`.
         */id: String) {
        self.typeName = typeName
        self.id = id
    }

    

    
}

#if compiler(>=6)
extension FfiEntityUid: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiEntityUid: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiEntityUid {
        return
            try FfiEntityUid(
                typeName: FfiConverterString.read(from: &buf), 
                id: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: FfiEntityUid, into buf: inout [UInt8]) {
        FfiConverterString.write(value.typeName, into: &buf)
        FfiConverterString.write(value.id, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiEntityUid_lift(_ buf: RustBuffer) throws -> FfiEntityUid {
    return try FfiConverterTypeFfiEntityUid.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiEntityUid_lower(_ value: FfiEntityUid) -> RustBuffer {
    return FfiConverterTypeFfiEntityUid.lower(value)
}


/**
 * The "type" of request an analysis is performed over: which principal type,
 * which action, which resource type.
 *
 * SymCC reasons one request environment at a time, so a question about a
 * whole policy set is really N questions. The caller chooses N — it knows
 * which environments can possibly matter and which are a waste of a solver
 * process.
 */
public struct FfiRequestEnv: Equatable, Hashable {
    /**
     * Fully-qualified principal entity type, e.g. `User`.
     */
    public var principalType: String
    /**
     * The action id, e.g. `vm:start` (the type is always `Action`).
     */
    public var action: String
    /**
     * Fully-qualified resource entity type, e.g. `Project`.
     */
    public var resourceType: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * Fully-qualified principal entity type, e.g. `User`.
         */principalType: String, 
        /**
         * The action id, e.g. `vm:start` (the type is always `Action`).
         */action: String, 
        /**
         * Fully-qualified resource entity type, e.g. `Project`.
         */resourceType: String) {
        self.principalType = principalType
        self.action = action
        self.resourceType = resourceType
    }

    

    
}

#if compiler(>=6)
extension FfiRequestEnv: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiRequestEnv: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiRequestEnv {
        return
            try FfiRequestEnv(
                principalType: FfiConverterString.read(from: &buf), 
                action: FfiConverterString.read(from: &buf), 
                resourceType: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: FfiRequestEnv, into buf: inout [UInt8]) {
        FfiConverterString.write(value.principalType, into: &buf)
        FfiConverterString.write(value.action, into: &buf)
        FfiConverterString.write(value.resourceType, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiRequestEnv_lift(_ buf: RustBuffer) throws -> FfiRequestEnv {
    return try FfiConverterTypeFfiRequestEnv.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiRequestEnv_lower(_ value: FfiRequestEnv) -> RustBuffer {
    return FfiConverterTypeFfiRequestEnv.lower(value)
}


/**
 * The result of an authorization query.
 */
public struct FfiResponse: Equatable, Hashable {
    public var decision: FfiDecision
    /**
     * Ids of the policies that contributed to the decision.
     */
    public var determiningPolicies: [String]
    /**
     * Evaluation errors encountered while deciding (does not imply Deny).
     */
    public var errors: [String]

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(decision: FfiDecision, 
        /**
         * Ids of the policies that contributed to the decision.
         */determiningPolicies: [String], 
        /**
         * Evaluation errors encountered while deciding (does not imply Deny).
         */errors: [String]) {
        self.decision = decision
        self.determiningPolicies = determiningPolicies
        self.errors = errors
    }

    

    
}

#if compiler(>=6)
extension FfiResponse: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiResponse: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiResponse {
        return
            try FfiResponse(
                decision: FfiConverterTypeFfiDecision.read(from: &buf), 
                determiningPolicies: FfiConverterSequenceString.read(from: &buf), 
                errors: FfiConverterSequenceString.read(from: &buf)
        )
    }

    public static func write(_ value: FfiResponse, into buf: inout [UInt8]) {
        FfiConverterTypeFfiDecision.write(value.decision, into: &buf)
        FfiConverterSequenceString.write(value.determiningPolicies, into: &buf)
        FfiConverterSequenceString.write(value.errors, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiResponse_lift(_ buf: RustBuffer) throws -> FfiResponse {
    return try FfiConverterTypeFfiResponse.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiResponse_lower(_ value: FfiResponse) -> RustBuffer {
    return FfiConverterTypeFfiResponse.lower(value)
}


/**
 * One validation error or warning.
 */
public struct FfiValidationIssue: Equatable, Hashable {
    public var policyId: String
    public var message: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(policyId: String, message: String) {
        self.policyId = policyId
        self.message = message
    }

    

    
}

#if compiler(>=6)
extension FfiValidationIssue: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiValidationIssue: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiValidationIssue {
        return
            try FfiValidationIssue(
                policyId: FfiConverterString.read(from: &buf), 
                message: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: FfiValidationIssue, into buf: inout [UInt8]) {
        FfiConverterString.write(value.policyId, into: &buf)
        FfiConverterString.write(value.message, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiValidationIssue_lift(_ buf: RustBuffer) throws -> FfiValidationIssue {
    return try FfiConverterTypeFfiValidationIssue.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiValidationIssue_lower(_ value: FfiValidationIssue) -> RustBuffer {
    return FfiConverterTypeFfiValidationIssue.lower(value)
}


public struct FfiValidationResult: Equatable, Hashable {
    public var passed: Bool
    public var errors: [FfiValidationIssue]
    public var warnings: [FfiValidationIssue]

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(passed: Bool, errors: [FfiValidationIssue], warnings: [FfiValidationIssue]) {
        self.passed = passed
        self.errors = errors
        self.warnings = warnings
    }

    

    
}

#if compiler(>=6)
extension FfiValidationResult: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiValidationResult: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiValidationResult {
        return
            try FfiValidationResult(
                passed: FfiConverterBool.read(from: &buf), 
                errors: FfiConverterSequenceTypeFfiValidationIssue.read(from: &buf), 
                warnings: FfiConverterSequenceTypeFfiValidationIssue.read(from: &buf)
        )
    }

    public static func write(_ value: FfiValidationResult, into buf: inout [UInt8]) {
        FfiConverterBool.write(value.passed, into: &buf)
        FfiConverterSequenceTypeFfiValidationIssue.write(value.errors, into: &buf)
        FfiConverterSequenceTypeFfiValidationIssue.write(value.warnings, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiValidationResult_lift(_ buf: RustBuffer) throws -> FfiValidationResult {
    return try FfiConverterTypeFfiValidationResult.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiValidationResult_lower(_ value: FfiValidationResult) -> RustBuffer {
    return FfiConverterTypeFfiValidationResult.lower(value)
}


public 
enum CedarError: Swift.Error, Equatable, Hashable, Foundation.LocalizedError {

    
    
    case ParseError(message: String
    )
    case EntitiesError(message: String
    )
    case SchemaError(message: String
    )
    case RequestError(message: String
    )
    case JsonError(message: String
    )
    case InternalError(message: String
    )
    /**
     * The SMT solver could not be started, died, or timed out. Distinct from
     * `AnalysisError` because it says the question went unanswered rather
     * than that the answer was no — callers that fail closed need to tell
     * those apart.
     */
    case SolverError(message: String
    )
    /**
     * The symbolic compiler rejected the query itself: a policy that is not
     * well-typed for the request environment, an action absent from the
     * schema, an unsupported construct.
     */
    case AnalysisError(message: String
    )

    

    

    
    public var errorDescription: String? {
        String(reflecting: self)
    }
    
}

#if compiler(>=6)
extension CedarError: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeCedarError: FfiConverterRustBuffer {
    typealias SwiftType = CedarError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> CedarError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .ParseError(
            message: try FfiConverterString.read(from: &buf)
            )
        case 2: return .EntitiesError(
            message: try FfiConverterString.read(from: &buf)
            )
        case 3: return .SchemaError(
            message: try FfiConverterString.read(from: &buf)
            )
        case 4: return .RequestError(
            message: try FfiConverterString.read(from: &buf)
            )
        case 5: return .JsonError(
            message: try FfiConverterString.read(from: &buf)
            )
        case 6: return .InternalError(
            message: try FfiConverterString.read(from: &buf)
            )
        case 7: return .SolverError(
            message: try FfiConverterString.read(from: &buf)
            )
        case 8: return .AnalysisError(
            message: try FfiConverterString.read(from: &buf)
            )

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: CedarError, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case let .ParseError(message):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(message, into: &buf)
            
        
        case let .EntitiesError(message):
            writeInt(&buf, Int32(2))
            FfiConverterString.write(message, into: &buf)
            
        
        case let .SchemaError(message):
            writeInt(&buf, Int32(3))
            FfiConverterString.write(message, into: &buf)
            
        
        case let .RequestError(message):
            writeInt(&buf, Int32(4))
            FfiConverterString.write(message, into: &buf)
            
        
        case let .JsonError(message):
            writeInt(&buf, Int32(5))
            FfiConverterString.write(message, into: &buf)
            
        
        case let .InternalError(message):
            writeInt(&buf, Int32(6))
            FfiConverterString.write(message, into: &buf)
            
        
        case let .SolverError(message):
            writeInt(&buf, Int32(7))
            FfiConverterString.write(message, into: &buf)
            
        
        case let .AnalysisError(message):
            writeInt(&buf, Int32(8))
            FfiConverterString.write(message, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCedarError_lift(_ buf: RustBuffer) throws -> CedarError {
    return try FfiConverterTypeCedarError.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCedarError_lower(_ value: CedarError) -> RustBuffer {
    return FfiConverterTypeCedarError.lower(value)
}



public enum FfiDecision: Equatable, Hashable {
    
    case allow
    case deny





}

#if compiler(>=6)
extension FfiDecision: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiDecision: FfiConverterRustBuffer {
    typealias SwiftType = FfiDecision

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiDecision {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .allow
        
        case 2: return .deny
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: FfiDecision, into buf: inout [UInt8]) {
        switch value {
        
        
        case .allow:
            writeInt(&buf, Int32(1))
        
        
        case .deny:
            writeInt(&buf, Int32(2))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiDecision_lift(_ buf: RustBuffer) throws -> FfiDecision {
    return try FfiConverterTypeFfiDecision.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiDecision_lower(_ value: FfiDecision) -> RustBuffer {
    return FfiConverterTypeFfiDecision.lower(value)
}




public enum FfiValidationMode: Equatable, Hashable {
    
    case strict
    case permissive





}

#if compiler(>=6)
extension FfiValidationMode: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiValidationMode: FfiConverterRustBuffer {
    typealias SwiftType = FfiValidationMode

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiValidationMode {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .strict
        
        case 2: return .permissive
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: FfiValidationMode, into buf: inout [UInt8]) {
        switch value {
        
        
        case .strict:
            writeInt(&buf, Int32(1))
        
        
        case .permissive:
            writeInt(&buf, Int32(2))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiValidationMode_lift(_ buf: RustBuffer) throws -> FfiValidationMode {
    return try FfiConverterTypeFfiValidationMode.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiValidationMode_lower(_ value: FfiValidationMode) -> RustBuffer {
    return FfiConverterTypeFfiValidationMode.lower(value)
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeFfiSchema: FfiConverterRustBuffer {
    typealias SwiftType = FfiSchema?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeFfiSchema.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeFfiSchema.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceString: FfiConverterRustBuffer {
    typealias SwiftType = [String]

    public static func write(_ value: [String], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterString.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String] {
        let len: Int32 = try readInt(&buf)
        var seq = [String]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterString.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeFfiPolicy: FfiConverterRustBuffer {
    typealias SwiftType = [FfiPolicy]

    public static func write(_ value: [FfiPolicy], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeFfiPolicy.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [FfiPolicy] {
        let len: Int32 = try readInt(&buf)
        var seq = [FfiPolicy]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeFfiPolicy.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeFfiValidationIssue: FfiConverterRustBuffer {
    typealias SwiftType = [FfiValidationIssue]

    public static func write(_ value: [FfiValidationIssue], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeFfiValidationIssue.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [FfiValidationIssue] {
        let len: Int32 = try readInt(&buf)
        var seq = [FfiValidationIssue]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeFfiValidationIssue.read(from: &buf))
        }
        return seq
    }
}
private let UNIFFI_RUST_FUTURE_POLL_READY: Int8 = 0
private let UNIFFI_RUST_FUTURE_POLL_WAKE: Int8 = 1

fileprivate let uniffiContinuationHandleMap = UniffiHandleMap<UnsafeContinuation<Int8, Never>>()

fileprivate func uniffiRustCallAsync<F, T>(
    rustFutureFunc: () -> UInt64,
    pollFunc: (UInt64, @escaping UniffiRustFutureContinuationCallback, UInt64) -> (),
    completeFunc: (UInt64, UnsafeMutablePointer<RustCallStatus>) -> F,
    freeFunc: (UInt64) -> (),
    liftFunc: (F) throws -> T,
    errorHandler: ((RustBuffer) throws -> Swift.Error)?
) async throws -> T {
    // Make sure to call the ensure init function since future creation doesn't have a
    // RustCallStatus param, so doesn't use makeRustCall()
    uniffiEnsureCedarFfiInitialized()
    let rustFuture = rustFutureFunc()
    defer {
        freeFunc(rustFuture)
    }
    var pollResult: Int8;
    repeat {
        pollResult = await withUnsafeContinuation {
            pollFunc(
                rustFuture,
                { handle, pollResult in
                    uniffiFutureContinuationCallback(handle: handle, pollResult: pollResult)
                },
                uniffiContinuationHandleMap.insert(obj: $0)
            )
        }
    } while pollResult != UNIFFI_RUST_FUTURE_POLL_READY

    return try liftFunc(makeRustCall(
        { completeFunc(rustFuture, $0) },
        errorHandler: errorHandler
    ))
}

// Callback handlers for an async calls.  These are invoked by Rust when the future is ready.  They
// lift the return value or error and resume the suspended function.
fileprivate func uniffiFutureContinuationCallback(handle: UInt64, pollResult: Int8) {
    if let continuation = try? uniffiContinuationHandleMap.remove(handle: handle) {
        continuation.resume(returning: pollResult)
    } else {
        print("uniffiFutureContinuationCallback invalid handle")
    }
}
/**
 * The version of the underlying cedar-policy engine.
 */
public func cedarVersion() -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
        uniffiCallStatus in
    uniffi_cedar_ffi_fn_func_cedar_version(uniffiCallStatus
    )
})
}
/**
 * Validate a policy set against a schema.
 */
public func validatePolicies(schema: FfiSchema, policies: FfiPolicySet, mode: FfiValidationMode) -> FfiValidationResult  {
    return try!  FfiConverterTypeFfiValidationResult_lift(try! rustCall() {
        uniffiCallStatus in
    uniffi_cedar_ffi_fn_func_validate_policies(
        FfiConverterTypeFfiSchema_lower(schema),
        FfiConverterTypeFfiPolicySet_lower(policies),
        FfiConverterTypeFfiValidationMode_lower(mode),uniffiCallStatus
    )
})
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 30
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_cedar_ffi_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_cedar_ffi_checksum_func_cedar_version() != 20018) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_cedar_ffi_checksum_func_validate_policies() != 20727) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_cedar_ffi_checksum_method_ffiauthorizer_is_authorized() != 16) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_cedar_ffi_checksum_method_ffientities_to_json() != 8184) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_cedar_ffi_checksum_method_ffipolicy_annotation() != 30026) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_cedar_ffi_checksum_method_ffipolicy_id() != 54468) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_cedar_ffi_checksum_method_ffipolicy_to_cedar() != 7003) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_cedar_ffi_checksum_method_ffipolicy_to_json() != 53726) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_cedar_ffi_checksum_method_ffipolicyset_is_empty() != 54758) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_cedar_ffi_checksum_method_ffipolicyset_policy_ids() != 29641) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_cedar_ffi_checksum_method_ffipolicyset_to_cedar() != 52077) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_cedar_ffi_checksum_method_ffisymboliccompiler_check_disjoint() != 48132) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_cedar_ffi_checksum_method_ffisymboliccompiler_check_implies() != 41519) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_cedar_ffi_checksum_constructor_ffiauthorizer_new() != 37195) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_cedar_ffi_checksum_constructor_ffientities_empty() != 47773) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_cedar_ffi_checksum_constructor_ffientities_from_json() != 39178) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_cedar_ffi_checksum_constructor_ffipolicy_from_json() != 18550) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_cedar_ffi_checksum_constructor_ffipolicy_parse() != 22321) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_cedar_ffi_checksum_constructor_ffipolicyset_empty() != 57127) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_cedar_ffi_checksum_constructor_ffipolicyset_from_policies() != 61770) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_cedar_ffi_checksum_constructor_ffipolicyset_parse() != 55866) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_cedar_ffi_checksum_constructor_ffischema_from_json() != 4355) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_cedar_ffi_checksum_constructor_ffischema_parse() != 22171) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_cedar_ffi_checksum_constructor_ffisymboliccompiler_new() != 48893) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsureCedarFfiInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all